name: shortly
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^4.0.0
  shared_preferences: ^2.0.7
  dio: ^4.0.0
  share: ^2.0.4
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/appstore.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/illustration.svg
    - asset/images/logo.svg
    - asset/images/shape.svg
    - asset/images/del.svg
  

  